package cnd

// Card conditions
const (
	SummoningSickness   = "summoning_sickness"
	DoubleBreaker       = "doublebreaker"
	TripleBreaker       = "triplebreaker"
	ShieldBreakModifier = "shieldbreak_modifier"
	PowerAmplifier      = "power_amplifier"
	PowerAttacker       = "power_attacker"
	AttackUntapped      = "attack_untapped"
	Creature            = "creature"
	Spell               = "spell"
	Blocker             = "blocker"
	ShieldTrigger       = "shield_trigger"
	Slayer              = "slayer"
	Active              = "active"
	CantBeBlocked       = "cant_be_blocked"
	CantAttackCreatures = "cant_attack_creatures"
	CantAttackPlayers   = "cant_attack_players"
	ReducedCost         = "reduced_cost"
	IncreasedCost       = "increased_cost"
	Evolution           = "evolution"
	Survivor            = "survivor"
	SpeedAttacker       = "Speed Attacker"
	EvolveIntoAnyFamily = "evolve_into_any_family"
	TapAbility          = "tap_ability"
	DestroyAfterBattle  = "destroy_after_battle"
	CantBeAttacked      = "cant_be_attacked"
	Stealth             = "stealth"
	AddFamily           = "add_family"
)
