package family

// Families
const (
	MachineEater    = "Machine Eater"
	Berserker       = "Berserker"
	BeastFolk       = "Beast Folk"
	ArmoredDragon   = "Armored Dragon"
	ArmoredWyvern   = "Armored Wyvern"
	ColonyBeetle    = "Colony Beetle"
	HornedBeast     = "Horned Beast"
	Leviathan       = "Leviathan"
	CyberVirus      = "Cyber Virus"
	GelFish         = "Gel Fish"
	BalloonMushroom = "Balloon Mushroom"
	LivingDead      = "Living Dead"
	AngelCommand    = "Angel Command"
	Chimera         = "Chimera"
	DemonCommand    = "Demon Command"
	CyberLord       = "Cyber Lord"
	LiquidPeople    = "Liquid People"
	Initiate        = "Initiate"
	RockBeast       = "Rock Beast"
	GiantInsect     = "Giant Insect"
	Ghost           = "Ghost"
	Dragonoid       = "Dragonoid"
	LightBringer    = "Light Bringer"
	StarlightTree   = "Starlight Tree"
	Human           = "Human"
	Guardian        = "Guardian"
	ParasiteWorm    = "Parasite Worm"
	Armorloid       = "Armorloid"
	TreeFolk        = "Tree Folk"
	Fish            = "Fish"
	DarkLord        = "Dark Lord"
	BrainJacker     = "Brain Jacker"
	Giant           = "Giant"
	MechaThunder    = "Mecha Thunder"
	CyberCluster    = "Cyber Cluster"
	Hedrian         = "Hedrian"
	FireBird        = "Fire Bird"
	RainbowPhantom  = "Rainbow Phantom"
	Gladiator       = "Gladiator"
	SeaHacker       = "Sea Hacker"
	EarthEater      = "Earth Eater"
	DeathPuppet     = "Death Puppet"
	DevilMask       = "Devil Mask"
	Xenoparts       = "Xenoparts"
	DuneGecko       = "Dune Gecko"
	SnowFaerie      = "Snow Faerie"
	MysteryTotem    = "Mystery Totem"
	Survivor        = "Survivor"
	VolcanoDragon   = "Volcano Dragon"
	EarthDragon     = "Earth Dragon"
	ZombieDragon    = "Zombie Dragon"
	MechaDelSol     = "Mecha del Sol"
)

var Cybers = []string{CyberCluster, CyberLord, CyberVirus}
var Dragons = []string{ArmoredDragon, VolcanoDragon, EarthDragon, ZombieDragon}
